spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: "000000"

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.studentmanagementweb.dao: debug   # 打印 SQL 日志，方便调试
    com.example.studentmanagementweb: debug

  logging:
    level:
      root: info                    # 全局 info
      com.example.studentmanagementweb: debug  # 你的包打印 debug
      org.springframework.web: info
      org.mybatis: debug